### ISSUE TITLE
Odd default data/types for many events

### ISSUE THREAD

**Issue by goto-bus-stop** [SooYou/plugged#13]
Mostly the strings. It's sometimes due to plug not having a consistent API, but sometimes just generally odd as well.

 * If a user doesn't have a slug, it's set to the empty string
 * If a media item doesn't exist (eg. an ADVANCE event when the only DJ stops playing), it defaults to a media item with a cid of `""` (and some other "zero", but non-null data)

Ideally, an ADVANCE event when no new song starts playing, would just get `null` (intentional absence) for the next play, because there is no next play. Then developers can simply use `!== null` to check if the media item exists. Even nicer, you'll just get `null` from `getCurrentMedia`, too, so you don't have to do `media.cid !== ''` afterward.

If a user doesn't have a slug, the property should either be `null` or just not exist at all. Preferably the latter, because copying properties onto eg. a database model will override empty properties, too. This also goes for USER_UPDATEs especially, because usually only one property of the five possible updates is set.

So the main proposal here is to let plugged report absence, when data is absent. Preferably by returning `null` as a default for most things (except where defaults really make sense) and sometimes by omitting properties entirely.

(Also, semi-related, return `Date` instances where appropriate, instead of strings with preformatted dates)

Changes to these would be breaking, so it might be something for a 3.0 release :smile:

**Comment by SooYou** [comment]
since plug was shut down a few days ago this won't happen anymore.
