### ISSUE TITLE
Create Playlist

### ISSUE THREAD

**Issue by vinicios-yals** [SooYou/plugged#14]
How do I create a playlist using the plugged API?

**Comment by SooYou** [comment]
The function for that is called
```JavaAcript
addPlaylist(name, mediaArray, callback);
```

Right now, plugged expects the mediaArray to be filled with objects from youtube's or soundcloud's search queries, which will be optional with 2.5.0 in the coming days.

Here is an example
```JavaScript
var ytObj = {
    "title": "Olly Murs - Army Of Two",
    "id": "MZKsZM2E4rI",
    "thumbnails": {
        "default": {
            "url": "https://i.ytimg.com/vi/MZKsZM2E4rI/default.jpg"
        }
    }
};

plugged.addPlaylist("testPlaylist", [ytObj], function(err, playlist) {
    console.log(err);
    console.log(playlist);
}
```

Hope that helps.

If you have any other question feel free to ask!

**Comment by vinicios-yals** [comment]
This function don't exists in your documentation =)

Thanks!

**Comment by vinicios-yals** [comment]
Wops, one more question, I can put ID instead playlist name?

**Comment by SooYou** [comment]
The documentation is lacking a few functions still but will see more attention soon :laughing:
