### ISSUE TITLE
Randomly disconnects, suspects session gets invalidated.

### ISSUE THREAD

**Issue by Foorack** [SooYou/plugged#16]
The bot randomly times out after a period of 2 songs (5 min) and stops functioning completely.
I suspect it's the session which gets invalidated. The callback gets ran but the action (i.e. skip) does is not actually performed.

Do you know how One would refresh the session without complete restart?

**Comment by SooYou** [comment]
Plug is dead, I presume you are using the staging branch which users are not even supposed to be on. It's quite likely that this, as well, will be gone soon.

Have a nice christmas.
