### ISSUE TITLE
Cannot find ./conf/config

### ISSUE THREAD

**Issue by Fuechschen** [SooYou/plugged#17]
It seems like conf/config.json isn't included in the npm-package...

**Comment by SooYou** [comment]
1ab5f24156ac6a22b72cbeb577c8c20771558d23 fixes this.

I simply forgot to put the conf/config.json inside the files array in package.json, kind of stuff that happens when not using npm for a while haha, surprisingly the testbed passed successfully.

Good catch and thanks for informing!
