### ISSUE TITLE
Plugged.prototype.getCSRF fails

### ISSUE THREAD

**Issue by Nodle** [SooYou/plugged#22]
plug.dj has updated their website.
This has caused `var idx = body.indexOf("_csrf") + 7;` to be incorrect.
At a minimum it needs to be updated to `var idx = body.indexOf("_csrf") + 9;` to work currently.

Slightly more robust method would be to work out the space between `var _csrf` and the start of the csrf
```
        var idx = body.indexOf("_csrf");
        var idx = idx + body.indexOf('\"', idx) - idx + 1;
```

The best solution would be to make use of https://plug.dj/_/mobile/init which has the csrf and other variables in JSON format.

**Comment by SooYou** [comment]
Hey Nodle,

thanks for your input! I will apply the hotfix asap.
To the link, that's great information! It makes the whole startup a tad faster on slower connections too.

Plugged is currently in the transition to 3.0.0 but sadly university is keeping me plenty busy so it's still an ongoing process. will make sure that 3.0.0 will use the /init route then!

greetings
Sooyou
