### ISSUE TITLE
Common Problems

### ISSUE THREAD

**Issue by viniciosyals** [SooYou/plugged#31]
In [Docs](https://sooyou.github.io/plugged/reference/functions.html#removechatmessagebyuser) the command is named with `removeChatMessageByUser()` but in the plugged.js methods is named with `removeChatMessagesByUser()`

and

This method not have username params
![](https://i.imgur.com/Lm7Wflq.png)

=)

**Comment by SooYou** [comment]
Hi viniciosyals,

thank you for opening the issue!
That's a good and very important find, a fix will be available ASAP.
If you are okay with it, I will also mention you in the *Thank you* section of the docs.
