### ISSUE TITLE
Audio Forwarding?

### ISSUE THREAD

**Issue by serapath** [SooYou/plugged#8]
Is it possible to grab the audio of the current song and forward it to somewhere else?

**Comment by SooYou** [comment]
while this is certainly possible, it is not part of plugged. It is basically beyond the scope of the project. You can get all informations from plugged and then use the appropiate tools to fetch the audio from soundcloud and youtube and pipe it to your player of choice.

**Comment by serapath** [comment]
thx :-)

**Comment by SooYou** [comment]
sure thing~
